### ISSUE TITLE
Error 500--Unable to download document from proxied SharePoint

### ISSUE THREAD

**Issue by NadHodeGW** [k8-proxy/gp-sharepoint#8]
When a document download is triggered, it get cancelled and returns a 500 error

To replicate:
Pre-condition:
run through setup using the details in the repo: k8-gp-sharepoint
"Host details: 
34.244.17.60 saaspoc1.sharepoint.com saaspoc1-my.sharepoint.com ukc-word-edit.officeapps.live.com ukc-excel.officeapps.live.com  ukc-powerpoint.officeapps.live.com
Current Icap server in use: icap-client-main.uksouth.cloudapp.azure.com using ICAPS on port 1345"

Steps:
Go to https://saaspoc1.sharepoint.com/documents
With the network console opened, select any document & click download

Notice the error below

![image](https://user-images.githubusercontent.com/61200359/104161656-2221ea00-53eb-11eb-8da5-af523998e0c1.png)

**Comment by NourEddineX** [comment]
the icap server (icap-client-main.uksouth.cloudapp.azure.com) ip address keeps changing, the squid setup is problematic with resolving icap server over DNS, which cause the ip address hardcoded in the configuration to fail after the server's ip has changed.  

I've updated the configuration to use the icap://icap-client-main.uksouth.cloudapp.azure.com:1344/gw_rebuild as ICAP URL and hardcoded the IP address in /etc/hosts, and installed a cron tab to update the /etc/hosts record every 3 minutes.  
Despite being an ugly hack, it's better that what we had previously.

On the other hand, the icap server itself is currently hanging, it takes forever to process [a simple pdf file](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf) . please check it

**Comment by GINAGC** [comment]
@naderaly please review.

**Comment by GINAGC** [comment]
please review @NadHodeGW

**Comment by NadHodeGW** [comment]
@NourEddineX please update the icap endpoint to: icap-client-qa-main.uksouth.cloudapp.azure.com

**Comment by NourEddineX** [comment]
yes, I did it already, and I could be able to download files with no issues (other than it's taking more than 7 seconds to download a tiny pdf)

**Comment by NadHodeGW** [comment]
Failures due to the icap endpoint Uk south unstable with slow response.
Endpoint updated to: 78.159.113.46 -p 1344
Downloading now works ok.
